import 'package:career_counsellor/constants/constants.dart';
import 'package:career_counsellor/utils/utils.dart';
import 'package:career_counsellor/widgets/info_container.dart';
import 'package:career_counsellor/widgets/markdown_formatted_text.dart';
import 'package:flutter/material.dart';
import 'package:google_generative_ai/google_generative_ai.dart' as google_ai;
import 'package:gpt_markdown/gpt_markdown.dart';
import 'package:lottie/lottie.dart';

class ElaborateDetail extends StatefulWidget {
  const ElaborateDetail({
    super.key,
    required this.title,
    required this.career,
  });

  final String title;
  final String career;

  @override
  State<ElaborateDetail> createState() => _ElaborateDetailState();
}

class _ElaborateDetailState extends State<ElaborateDetail> {
  bool isLoading = true;
  String? errorMessage;
  String body = '';

  @override
  void initState() {
    super.initState();
    _generateContent();
  }

  Future<void> _generateContent() async {
    setState(() {
      isLoading = true;
    });
    final model = google_ai.GenerativeModel(
      model: 'gemini-1.5-flash',
      apiKey: GEMINI_API_KEY,
    );

    final prompt =
        'Elaborate on the ${widget.title} of ${widget.career} as a career.';

    final content = [google_ai.Content.text(prompt)];
    try {
      final result = await model.generateContent(content);
      setState(() {
        if (result.text != null) {
          String response = result.text!;
          body = response;
        }
        isLoading = false;
      });
    } catch (e) {
      setState(() {
        showSnackBar(context, 'Error: $e');
        isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          centerTitle: true,
        ),
        body: isLoading
            ? Center(
                child: Lottie.asset(
                  'assets/animations/ai-loader1.json',
                  width: screenWidth * 0.25,
                  height: screenWidth * 0.25,
                  fit: BoxFit.contain,
                ),
              )
            : errorMessage != null
                ? Center(
                    child: Text(
                      errorMessage!,
                      style: const TextStyle(color: Colors.red),
                    ),
                  )
                : SingleChildScrollView(
                    padding: EdgeInsets.all(screenWidth * 0.04),
                    child: Column(
                      children: [
                        GptMarkdown(
                          body,
                          style: const TextStyle(fontSize: 18),
                        ),
                        SizedBox(
                          height: screenWidth * 0.1,
                        ),
                        const InfoContainer(
                            text:
                                'This content is generated by AI and may sometimes contain inaccuracies or incomplete information. Please verify independently when necessary.')
                      ],
                    ),
                  ));
    // MarkDownFormattedText(markdownString: body));
  }
}
