import 'package:career_counsellor/constants/constants.dart';
import 'package:career_counsellor/utils/utils.dart';
import 'package:career_counsellor/widgets/info_container.dart';
import 'package:flutter/material.dart';
import 'package:google_generative_ai/google_generative_ai.dart' as google_ai;

class ElaborateDetail extends StatefulWidget {
  const ElaborateDetail({
    super.key,
    required this.title,
    required this.career,
  });

  final String title;
  final String career;

  @override
  State<ElaborateDetail> createState() => _ElaborateDetailState();
}

class _ElaborateDetailState extends State<ElaborateDetail> {
  bool isLoading = true;
  String? errorMessage;
  String body = '';

  @override
  void initState() {
    super.initState();
    _generateInitialRecommendations();
  }

  Future<void> _generateInitialRecommendations() async {
    setState(() {
      isLoading = true;
    });
    final model = google_ai.GenerativeModel(
      model: 'gemini-1.5-flash',
      apiKey: Constants.GEMINI_API_KEY,
    );

    final prompt =
        'Elaborate on the ${widget.title} of ${widget.career} as a career.';

    final content = [google_ai.Content.text(prompt)];
    try {
      final result = await model.generateContent(content);
      setState(() {
        if (result.text != null) {
          String recommendations = result.text!;
          body = recommendations;
        }
        isLoading = false;
      });
    } catch (e) {
      setState(() {
        showSnackBar(context, 'Error: $e');
        isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Career Pathway'),
        centerTitle: true,
      ),
      body: isLoading
          ? const Center(child: CircularProgressIndicator())
          : errorMessage != null
              ? Center(
                  child: Text(
                    errorMessage!,
                    style: const TextStyle(color: Colors.red),
                  ),
                )
              : SingleChildScrollView(
                  padding: EdgeInsets.all(screenWidth * 0.04),
                  child: Column(
                    children: [
                      SelectableText(
                        body,
                        style: const TextStyle(fontSize: 16.0),
                      ),
                      SizedBox(
                        height: screenHeight * 0.03,
                      ),
                      const InfoContainer(
                          text:
                              'This content is generated by AI and may sometimes contain inaccuracies or incomplete information. Please verify independently when necessary.')
                    ],
                  ),
                ),
    );
  }
}
